global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

route:
  group_by: ['instance', 'severity','alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: 'discord_webhook'

# receivers:
# - name: 'email-notifications'
#   email_configs:
#   - to: 'admin@example.com'

receivers:
- name: 'discord_webhook'
  webhook_configs:
  - url: http://prometheus-discord:9094/



