global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# groups:
# - name: example
#   rules:
#   - alert: InstanceDown
#     expr: vector(1)
#     for: 1s
#     labels:
#       severity: "critical"
#     annotations:
#       summary: "Instance {{ $labels.instance }} down"
#       description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
