version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ${PROMETHEUS_CONFIG_PATH}:/etc/prometheus/prometheus-values.yml
      - ${ALERTS}:/etc/prometheus/alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus-values.yml'
    env_file:
      - .env
    ports:
      - 9090:9090
    networks:
      - monitoreo

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoreo

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: on-failure
    ports:
      - "9093:9093"
    volumes:
      - ${ALERTMANAGER_CONFIG_PATH}:/etc/alertmanager/alertmanager-values.yml
    command: --config.file=/etc/alertmanager/alertmanager-values.yml --cluster.advertise-address=0.0.0.0:9093
    env_file:
      - .env
    networks:
      - monitoreo

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ${PROMTAIL_CONFIG_PATH}:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    env_file:
      - .env
    networks:
      - monitoreo
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    devices:
      - /dev/kmsg
    ports:
      - "8080:8080"
    networks:
      - monitoreo

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    networks:
      - monitoreo
    depends_on:
      - promtail

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoreo
    environment:
      GF_SECURITY_ADMIN_PASSWORD: test%
    depends_on:
      - prometheus
      - loki

networks:
  monitoreo: