global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'loki'
    scrape_interval: 10s
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'cadvisor'
    scrape_interval: 10s 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'grafana'
    scrape_interval: 10s 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']


rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']